# fly.toml app configuration file generated for zentari-next-engine on 2025-12-27T23:39:39Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'zentari-next-engine'
primary_region = 'ewr'

[build]

# This is a background worker, not an HTTP service
# It runs continuously and doesn't need to listen on a port

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
